#!/bin/bash

set -e

is_systemd() {
    [ "$(basename "$(readlink -f /proc/1/exe 2>/dev/null)" 2>/dev/null)" = "systemd" ]
}

case "$1" in
    install|upgrade)
        if is_systemd; then
            if systemctl --quiet is-active rustdesk.service 2>/dev/null; then
                systemctl stop rustdesk.service >/dev/null 2>&1 || true
            fi
            sleep 1
            rm -f /usr/bin/libsciter-gtk.so
        fi
        ;;
esac

exit 0
